{application,mua,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{mua_app,[]}},
              {env,[]},
              {modules,[conn_man,mua_app,mua_handler,mua_sup,sock_server,
                        tcp]}]}.
